# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build investment-income-tax`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t investment-income-tax`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system investment-income-tax && \
          adduser --system -G investment-income-tax investment-income-tax

COPY dist/investment-income-tax investment-income-tax/
RUN chown -R investment-income-tax:investment-income-tax .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix investment-income-tax --omit=dev -f install

CMD [ "node", "investment-income-tax" ]
