name: Docker Build/Push Workflow
description: Build and Push Image to Docker Registry

inputs:
  docker-image-path:
    description: 'Docker image path, e.g. apps/server'
    required: true
  docker-registry:
    description: 'Docker registry name, e.g. registry.hub.docker.com'
    default: 'registry.hub.docker.com'
    required: false
  docker-tag:
    description: 'Docker tag, e.g. dev'
    default: 'latest'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Determine git commit hash
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      shell: bash

    - name: Check if image exists
      run: |
        IMAGE_EXISTS=$(docker pull ${{ inputs.docker-registry }}/${{ inputs.docker-image-path }}:$COMMIT_HASH > /dev/null 2>&1 && echo true || echo false)
        echo "IMAGE_EXISTS=$IMAGE_EXISTS" >> $GITHUB_ENV
      shell: bash

    - name: Build and tag Docker image
      if: env.IMAGE_EXISTS == 'false' || inputs.docker-tag != 'latest'
      run: |
        docker build -t ${{ inputs.docker-image-path }}:$COMMIT_HASH .
        docker tag ${{ inputs.docker-image-path }}:$COMMIT_HASH ${{ inputs.docker-registry }}/${{ inputs.docker-image-path }}:$COMMIT_HASH
      shell: bash

    - name: Push Docker image to registry
      if: env.IMAGE_EXISTS == 'false' || inputs.docker-tag != 'latest'
      run: docker push ${{ inputs.docker-registry }}/${{ inputs.docker-image-path }}:$COMMIT_HASH
      shell: bash

    - name: Add custom tag
      run: docker tag ${{ inputs.docker-registry }}/${{ inputs.docker-image-path }}:$COMMIT_HASH ${{ inputs.docker-registry }}/${{ inputs.docker-image-path }}:${{ inputs.docker-tag }}
      shell: bash

    - name: Push custom tag to registry
      run: docker push ${{ inputs.docker-registry }}/${{ inputs.docker-image-path }}:${{ inputs.docker-tag }}
      shell: bash
