name: CI/CD DEV Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ci-cd-dev
  cancel-in-progress: true

jobs:
  lint-test-build:
    name: Lint/Test/Build Job
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/lint-test-build.yml

  build-and-push:
    needs: lint-test-build
    environment:
      name: DEV
      url: https://dev.tax.uamanager.dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Step
        uses: actions/checkout@v4

      - name: Setup AWS Step
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image Step
        uses: ./.github/actions/docker/docker-build-push
        with:
          docker-path: ${{ vars.DOCKER_PATH }}
          docker-registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com